# Generated by Django 4.2.5 on 2023-09-30 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task2app', '0002_alter_order_date_ordered_alter_product_date_reg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.date(2023, 9, 30)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_reg',
            field=models.DateField(default=datetime.date(2023, 9, 30)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_reg',
            field=models.DateField(default=datetime.date(2023, 9, 30)),
        ),
    ]
