# Generated by Django 4.2.5 on 2023-10-01 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task2app', '0003_product_image_alter_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.date(2023, 10, 1)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_reg',
            field=models.DateField(default=datetime.date(2023, 10, 1)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_reg',
            field=models.DateField(default=datetime.date(2023, 10, 1)),
        ),
    ]
