# Generated by Django 4.2.5 on 2023-10-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task2app', '0004_alter_order_date_ordered_alter_product_date_reg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
